CREATE TABLE COACH
(
    CoachId INT PRIMARY KEY NOT NULL IDENTITY,
    CoachFName VARCHAR(30) NOT NULL,
    CoachLName VARCHAR(30) NOT NULL
);
CREATE TABLE PLAYER
(
    PlayerID INT PRIMARY KEY NOT NULL IDENTITY,
    JerseyNumber SMALLINT NOT NULL,
    FirstName VARCHAR(50) NOT NULL,
    LastName VARCHAR(50) NOT NULL,
    Position VARCHAR(5) NOT NULL,
    Age SMALLINT NOT NULL,
    Height VARCHAR(5) NOT NULL,
    Weight SMALLINT NOT NULL,
    College VARCHAR(75),
    Salary MONEY
);
CREATE TABLE ROSTER
(
    TeamID INT,
    PlayerID INT,
    coach INT,
    CONSTRAINT FK__ROSTER__TeamID__1367E606 FOREIGN KEY (TeamID) REFERENCES TEAM (TeamID),
    CONSTRAINT FK__ROSTER__PlayerID__145C0A3F FOREIGN KEY (PlayerID) REFERENCES PLAYER (PlayerID),
    CONSTRAINT FK__ROSTER__coach__173876EA FOREIGN KEY (coach) REFERENCES COACH (CoachId)
);
CREATE TABLE TEAM
(
    TeamID INT PRIMARY KEY NOT NULL IDENTITY,
    City VARCHAR(15) NOT NULL,
    TeamName VARCHAR(15) NOT NULL,
    Wins SMALLINT,
    Losses SMALLINT
);