INSERT INTO NBA.dbo.TEAM (City, TeamName, Wins, Losses) VALUES ('Atlanta', 'Hawks', null, null);
INSERT INTO NBA.dbo.TEAM (City, TeamName, Wins, Losses) VALUES ('Boston', 'Celtics', null, null);
INSERT INTO NBA.dbo.TEAM (City, TeamName, Wins, Losses) VALUES ('Brooklyn', 'Nets', null, null);
INSERT INTO NBA.dbo.TEAM (City, TeamName, Wins, Losses) VALUES ('Charlotte', 'Hornets', null, null);
INSERT INTO NBA.dbo.TEAM (City, TeamName, Wins, Losses) VALUES ('Chicago', 'Bulls', null, null);
INSERT INTO NBA.dbo.TEAM (City, TeamName, Wins, Losses) VALUES ('Cleveland', 'Cavaliers', null, null);
INSERT INTO NBA.dbo.TEAM (City, TeamName, Wins, Losses) VALUES ('Dallas', 'Mavericks', null, null);
INSERT INTO NBA.dbo.TEAM (City, TeamName, Wins, Losses) VALUES ('Denver', 'Nuggets', null, null);
INSERT INTO NBA.dbo.TEAM (City, TeamName, Wins, Losses) VALUES ('Detroit', 'Pistons', null, null);
INSERT INTO NBA.dbo.TEAM (City, TeamName, Wins, Losses) VALUES ('Golden State', 'Warriors', null, null);
INSERT INTO NBA.dbo.TEAM (City, TeamName, Wins, Losses) VALUES ('Houston', 'Rockets', null, null);
INSERT INTO NBA.dbo.TEAM (City, TeamName, Wins, Losses) VALUES ('Indiana', 'Pacers', null, null);
INSERT INTO NBA.dbo.TEAM (City, TeamName, Wins, Losses) VALUES ('Los Angeles', 'Clippers', null, null);
INSERT INTO NBA.dbo.TEAM (City, TeamName, Wins, Losses) VALUES ('Los Angeles', 'Lakers', null, null);
INSERT INTO NBA.dbo.TEAM (City, TeamName, Wins, Losses) VALUES ('Memphis', 'Grizzlies', null, null);
INSERT INTO NBA.dbo.TEAM (City, TeamName, Wins, Losses) VALUES ('Miami', 'Heat', null, null);
INSERT INTO NBA.dbo.TEAM (City, TeamName, Wins, Losses) VALUES ('Milwaukee', 'Bucks', null, null);
INSERT INTO NBA.dbo.TEAM (City, TeamName, Wins, Losses) VALUES ('Minnesota', 'Timberwolves', null, null);
INSERT INTO NBA.dbo.TEAM (City, TeamName, Wins, Losses) VALUES ('New Orleans', 'Pelicans', null, null);
INSERT INTO NBA.dbo.TEAM (City, TeamName, Wins, Losses) VALUES ('New York', 'Knicks', null, null);
INSERT INTO NBA.dbo.TEAM (City, TeamName, Wins, Losses) VALUES ('Oklahoma City', 'Thunder', null, null);
INSERT INTO NBA.dbo.TEAM (City, TeamName, Wins, Losses) VALUES ('Orlando', 'Magic', null, null);
INSERT INTO NBA.dbo.TEAM (City, TeamName, Wins, Losses) VALUES ('Philadelphia', 'Sixers', null, null);
INSERT INTO NBA.dbo.TEAM (City, TeamName, Wins, Losses) VALUES ('Phoenix', 'Suns', null, null);
INSERT INTO NBA.dbo.TEAM (City, TeamName, Wins, Losses) VALUES ('Portland', 'TrailBlazers', null, null);
INSERT INTO NBA.dbo.TEAM (City, TeamName, Wins, Losses) VALUES ('Sacramento', 'Kings', null, null);
INSERT INTO NBA.dbo.TEAM (City, TeamName, Wins, Losses) VALUES ('San Antonio', 'Spurs', null, null);
INSERT INTO NBA.dbo.TEAM (City, TeamName, Wins, Losses) VALUES ('Toronto', 'Raptors', null, null);
INSERT INTO NBA.dbo.TEAM (City, TeamName, Wins, Losses) VALUES ('Utah', 'Jazz', null, null);
INSERT INTO NBA.dbo.TEAM (City, TeamName, Wins, Losses) VALUES ('Washington', 'Wizards', null, null);